fix: return non-zero if there were errors in processing
icub-tech-iit/outside-collaborators pull request #81
Opened 2021-09-28 16:24 UTC by renaissanceGeek

Fixes #80 very simply.  There may be something more elegant, but at least this helped my use case!

2021-09-28 17:53 UTC, pattacini requested changes
I like the simple logic @renaissanceGeek 👍🏻 
I'm just wondering if you're willing to deal also with the error conditions caught inside `add_repo_collaborator` that now won't make the job exit 1.

You may turn `has_errors` into a global var (e.g., `$has_errors`) as `$org`  to handle those 3 further conditions.

Instead, a better way would be to make `add_repo_collaborator` return false when one of those 3 exceptions occurs so that you'll be able to account for that with `has_errors` locally to the main.

### Just a note for myself
Differently from this logic, `check-automated-repositories` shall exit as soon as an exception gets found as it is done right now so that the PR check can provide immediate feedback.

2021-09-28 17:53 UTC, pattacini commented on scripts/outside-collaborators-handler.rb
> +                puts " - problem detected #{e.inspect}❌"
```suggestion
                puts " - problem detected: #{e.inspect}❌"
```

2021-09-28 22:32 UTC, renaissanceGeek commented
OK, I think I resolved your requests.  I tried testing various error conditions that could come up in add_repo-collaborator and successfully failed ;-)

2021-09-29 05:52 UTC, pattacini approved these changes
Fantastic job @renaissanceGeek 🚀 
I've only added a missing `return true` and dealt with just another call to the function.

Thanks again for your contribution!
Appreciated.

2021-09-29 05:52 UTC, merged